#!/usr/bin/env python3
"""Select GisAPR particles; emit two complete pickles from one serialization.

Requirements: Python >= 3.8, NumPy, SciPy; Matplotlib for the distribution plot.

Example (the v2p6 command line is still accepted)::

    python read_search_txt_pick_good_v3p3.py --i index.txt \
        --best_string rotN1p0_tiltN12p2_psi4p4deg_trans2p3_8p1_N4p8ANG \
        --o fortest --diameter 40 --top_N 5 --top_N_sum_threshold 2.5

v3p3 implementation and compatibility notes
-------------------------
* Follow v2p6's file filter before sorting or scoring: count physical text
  lines, ignore unreadable files, and keep only the most common line count.
  Both shorter and longer files are excluded. Repeated path strings count
  once, in first-occurrence index order; ties between line-count frequencies
  use that same order, exactly as v2p6's dict/Counter implementation does.
  Counting uses bounded text blocks with universal-newline handling. No
  full-file readlines or temporary arrays are used. The filter is checked
  on every invocation so repaired or newly missing files affect caching.
* The filename/best_string labels remain rot/tilt/psi. Their three values
  are rotation-vector components in degrees, NOT Euler angles. Match v2p6
  using SciPy Rotation.from_rotvec(deg2rad(...)), R1 * R2.inv(), magnitude(),
  and np.degrees, with the original scalar operation order.
* Optional selected search files are written only for the retained inputs;
  excluded files are skipped throughout. v2p6's optional export reopens the
  unfiltered index, which can attempt to read a missing/truncated file again.
* Call the original standard pickle.dump once on the complete raw list.
  Its unmodified byte stream is written to the raw pickle. A validated
  streaming parser copies the same stream to the Z-score pickle, changing
  only the float64 score payloads. Keys, distances, dtype metadata, memo
  opcodes, frames and byte order all come from the standard Pickler.
* The parser learns the regular NumPy-scalar record layout from a small
  pickle generated by this runtime. It checks complete record bytes against
  the source dictionary before replacing score payloads. A boundary parser
  handles initial dtype definitions, frames and partial records. It never
  searches for arbitrary float byte strings or unpickles its input.
* One serialization normally writes both final streams at once: no raw-file
  reread, no full-file bytes buffer, no disk-backed intermediate arrays,
  no second full dictionary, and no multiprocessing. Auxiliary patching
  buffers are bounded; Python integer byte counters support multi-GB files.
* On an unrecognized runtime layout, keep the completed standard raw pickle
  and automatically produce ZS with v3p1's standard second dump. This is
  explicitly reported. An I/O error aborts instead of being hidden.
* Keep the scalar operations used by v2p6 for score**2, mean**2, math.sqrt
  and Z-score normalization. Per-file float64 additions retain the original
  distance-sorted file order. No float32, approximate variance, FMA rewrite,
  or parallel reduction is used. rawCC/1024 is the source of the score.
* Stream input text, accumulate compact statistics, and directly build ONE
  full dictionary list. There is no array spool or full deepcopy.
  Standard pickle.dump's memo and the one full list do require memory
  proportional to total records. Unlike v3p0, memory is NOT O(particles).
* Compute top_N sums once and reuse them for all 61 histogram thresholds.
  Optional STAR/search output is still streamed; --max_cpu controls only
  optional search-file writing.
* Use a NEW <prefix>_pick_cache_v3p3.npz with runtime/input provenance.
  Earlier sidecars are never reused. Existing .pkl files without a matching
  v3p3 sidecar are regenerated, even without --regenerate_pickel. Threshold
  changes can reuse scores only while BOTH full pickle files still match.
* For an exact comparison, run both versions with --regenerate_pickel in
  the SAME Python/NumPy/SciPy environment, using the SAME input index/order,
  input files, best_string and diameter. Pickle bytes are runtime-dependent.
  --verify_against_prefix OLD_PREFIX compares both complete files using
  SHA-256 and fails if either differs. No reference pickle is executed.
* Preserve the legacy range(len(first_file_dictionary)) normalization and
  selection bound. Serials are zero-based physical STAR line numbers.
  Entries beyond that bound stay RAW in the Z-score pickle, as in v2p6.
  Inconsistent normalized serial coverage and negative variance remain
  errors; zero-variance normalization retains the original NaN behavior.
* --tmpdir is accepted for command-line compatibility but is no longer used
  for intermediate arrays. Both pickle files are staged before replacement.
  Partial new pickle data is not committed on an input, normalization or
  serialization error.
"""

import argparse
from array import array
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from contextlib import contextmanager
from itertools import chain
import hashlib
import json
import math
import os
import pickle
import pickletools
import platform
import re
import sys
import tempfile
import time

import numpy as np
import scipy
from scipy.spatial.transform import Rotation as R


__version__ = "3.3"
_TRANSFORM = re.compile(
    r"rot(?P<rot>[Np\d]+)_tilt(?P<tilt>[Np\d]+)_psi(?P<psi>[Np\d]+)"
    r"deg_trans(?P<x>[Np\d]+)_(?P<y>[Np\d]+)_(?P<z>[Np\d]+)ANG"
)
_CACHE_FORMAT = "gisapr-pick-v3p3-rotvec-modal-lines-single-dump-1"


def decode_transform_string(s):
    def convert(value):
        value = value.replace("p", ".")
        return -float(value[1:]) if value.startswith("N") else float(value)

    match = _TRANSFORM.search(s)
    if match is None:
        # Preserve v2p6's identity-transform fallback.
        return (0.0,) * 6
    return tuple(convert(match.group(k)) for k in ("rot", "tilt", "psi", "x", "y", "z"))


def calc_weight_between_distance_rotation(diameter):
    w0 = 360.0 / np.pi / diameter
    return 1.0 / w0


def compute_weighted_overall_distance(rotation_in_degree, translation_in_angstrom, weight):
    return np.sqrt((rotation_in_degree * weight) ** 2.0 + translation_in_angstrom ** 2.0)


def DEG2RAD(x):
    # Legacy helper retained for imports; pose distances now use rotvec.
    return x / 180.0 * 3.14159265359


def Euler_angles2matrix(alpha, beta, gamma):
    alpha, beta, gamma = DEG2RAD(alpha), DEG2RAD(beta), DEG2RAD(gamma)
    ca, cb, cg = math.cos(alpha), math.cos(beta), math.cos(gamma)
    sa, sb, sg = math.sin(alpha), math.sin(beta), math.sin(gamma)
    cc, cs, sc, ss = cb * ca, cb * sa, sb * ca, sb * sa
    return [
        [cg * cc - sg * sa, cg * cs + sg * ca, -cg * sb],
        [-sg * cc - cg * sa, -sg * cs + cg * ca, sg * sb],
        [sc, ss, cb],
    ]


def CLIP(a, b, c):
    if float(a) < float(b):
        return float(b)
    if float(a) > float(c):
        return float(c)
    return float(a)


def dotProduct(v1, v2):
    if len(v1) != len(v2):
        return -9999999.0
    result = 0.0
    for a, b in zip(v1, v2):
        result += float(a) * float(b)
    return result


def calculateAngularDistance(rot1, tilt1, psi1, rot2, tilt2, psi2):
    # These names encode rotation-vector components, not Euler angles.
    # Retain v2p6's scalar SciPy calls and operation order for exact floats.
    rot1 = np.deg2rad(rot1)
    rot2 = np.deg2rad(rot2)
    tilt1 = np.deg2rad(tilt1)
    tilt2 = np.deg2rad(tilt2)
    psi1 = np.deg2rad(psi1)
    psi2 = np.deg2rad(psi2)
    r1 = np.array([rot1, tilt1, psi1])
    r2 = np.array([rot2, tilt2, psi2])
    R1 = R.from_rotvec(r1)
    R2 = R.from_rotvec(r2)
    R_rel = R1 * R2.inv()
    angle = R_rel.magnitude()
    return np.degrees(angle)


def calculateShiftDistance(x, y, z, x1, y1, z1):
    a1, a2, a3 = (x1 - x) ** 2.0, (y1 - y) ** 2.0, (z1 - z) ** 2.0
    return math.sqrt(a1 + a2 + a3)


def read_index(filename):
    # Relative entries remain relative to the working directory, as in v2p6.
    with open(filename, "r") as handle:
        paths = [line.split()[0] for line in handle if line.split()]
    if not paths:
        raise ValueError("The input index contains no search files.")
    return paths


def count_search_lines(filename, block_size=4 * 1024 * 1024):
    """Match sum(1 for line in open(filename)), using bounded text blocks."""
    if block_size < 1:
        raise ValueError("Line-count block size must be positive.")
    count, last = 0, ""
    # Default text decoding and universal newlines match v2p6, including
    # CRLF/CR input and a final line without a newline terminator.
    with open(filename, "r") as handle:
        for block in iter(lambda: handle.read(block_size), ""):
            count += block.count("\n")
            last = block[-1]
    return count + int(bool(last) and last != "\n")


def filter_search_files(paths):
    """Keep v2p6's modal line-count group and its exact file/tie order."""
    unique_paths = list(dict.fromkeys(paths))
    line_counts = {}
    last_progress = time.monotonic()
    for index, path in enumerate(unique_paths, 1):
        try:
            line_counts[path] = count_search_lines(path)
        except (OSError, UnicodeError) as exc:
            print("Warning: cannot read {}, skip. ({})".format(path, exc), flush=True)
        now = time.monotonic()
        if now - last_progress >= 15:
            print("Counted lines in {}/{} search files".format(index, len(unique_paths)), flush=True)
            last_progress = now
    if not line_counts:
        raise ValueError("No readable search files remain after v2p6 line-count filtering.")
    # Counter breaks frequency ties by the first occurrence of a line count.
    most_common_count = Counter(line_counts.values()).most_common(1)[0][0]
    clean_files = []
    for path, count in line_counts.items():
        if count == most_common_count:
            clean_files.append(path)
        else:
            print("Warning: {} has {} lines; expected {} (most common), skip.".format(
                path, count, most_common_count), flush=True)
    print("Most common line count:", most_common_count)
    print("Total files:", len(paths))
    print("Valid files:", len(clean_files))
    print("Removed files:", len(paths) - len(clean_files))
    if len(unique_paths) != len(paths):
        print("Repeated index entries ignored:", len(paths) - len(unique_paths))
    return clean_files


def sorted_file_distances(paths, best_string, diameter):
    pivot = decode_transform_string(best_string)
    weight = calc_weight_between_distance_rotation(diameter)
    pairs = []
    for path in paths:
        pose = decode_transform_string(path)
        rotation = calculateAngularDistance(*(pivot[:3] + pose[:3]))
        translation = calculateShiftDistance(*(pivot[3:] + pose[3:]))
        pairs.append((path, compute_weighted_overall_distance(rotation, translation, weight)))
    # Python's stable sort preserves index.txt order for equal distances.
    pairs.sort(key=lambda pair: pair[1])
    return pairs


def read_search_scores(filename, distance):
    """Read native-int/float64 arrays, with dict-compatible last-wins IDs."""
    serials, scores, distances = array("q"), array("d"), array("d")
    with open(filename, "r") as handle:
        for record, first in enumerate(handle, 1):
            second, third = handle.readline(), handle.readline()
            if not second or not third:
                raise ValueError("{}: incomplete three-line record {}".format(filename, record))
            try:
                fields = first.split(",", 3)
                if len(fields) < 2:
                    raise ValueError("missing serial-number field")
                if fields[0] == "['cc: '":
                    serial = int(fields[1])
                    float(fields[2])  # v2p6 validates this unused input Z score.
                    score = float(third.rsplit(",", 1)[-1].split("]", 1)[0]) / 1024.0
                    record_distance = distance
                else:
                    # v2p6 maps all non-cc records to this single sentinel.
                    serial, score = -1, 0.0
                    record_distance = 999.0
                serials.append(serial)
                scores.append(score)
                distances.append(record_distance)
            except (ValueError, IndexError, OverflowError) as exc:
                raise ValueError("{}: invalid record {}: {}".format(filename, record, exc)) from exc
    ids = np.frombuffer(serials, dtype=np.int64)
    native_int = np.dtype(int)  # v2p6 uses np.zeros(..., dtype=int).
    if native_int != ids.dtype:
        limits = np.iinfo(native_int)
        if np.any((ids < limits.min) | (ids > limits.max)):
            raise ValueError("A serial number cannot be represented by NumPy's native integer dtype.")
        ids = ids.astype(native_int)
    raw = np.frombuffer(scores, dtype=np.float64)
    dist = np.frombuffer(distances, dtype=np.float64)
    if ids.size > 1 and not np.all(ids[1:] > ids[:-1]):
        unique, first_index = np.unique(ids, return_index=True)
        if unique.size != ids.size:
            # dict(zip(...)) keeps first insertion order but the last value.
            _, reversed_first = np.unique(ids[::-1], return_index=True)
            order = np.argsort(first_index)
            last_index = (ids.size - 1 - reversed_first)[order]
            raw, dist, ids = raw[last_index], dist[last_index], unique[order]
    return ids, raw, dist


@contextmanager
def atomic_binary_file(path):
    parent = os.path.dirname(os.path.abspath(path))
    os.makedirs(parent, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=".gisapr_pick_", dir=parent)
    try:
        with os.fdopen(fd, "w+b") as handle:
            yield handle
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def pickle_paths(prefix):
    return (prefix + "_serial_score_per_file.pkl",
            prefix + "_To_compute_ZS_serial_score_per_file.pkl")


class PickleLayoutError(ValueError):
    """The fast parser cannot prove that this stream has the expected layout."""


def scalar_record_layout(leading_empty):
    """Obtain a record fingerprint from this runtime's standard Pickler.

    Leading empty dictionaries matter because they change memo indices.
    FRAME bytes are excluded from the fingerprint, not from either output.
    """
    if pickle.DEFAULT_PROTOCOL not in (4, 5):
        raise PickleLayoutError("single-pass parsing requires pickle protocol 4 or 5")
    probe = [{} for _ in range(leading_empty)]
    probe.append({np.int_(i): (np.float64(i + 0.125), np.float64(i + 0.625)) for i in range(3)})
    blob = pickle.dumps(probe)
    ops = list(pickletools.genops(blob))
    tokens = []
    for i, (op, arg, start) in enumerate(ops):
        end = ops[i + 1][2] if i + 1 < len(ops) else len(blob)
        if op.name != "FRAME":
            tokens.append((op.name, arg, blob[start:end]))
    payloads = [i for i, (name, _, _) in enumerate(tokens) if name == "SHORT_BINBYTES"]
    if len(payloads) != 9:
        raise PickleLayoutError("unexpected NumPy scalar reduction layout")

    def extract(indices):
        first, _, last = indices
        if any(tokens[first - j][0] not in ("BINGET", "LONG_BINGET") for j in (1, 2)):
            raise PickleLayoutError("unexpected scalar constructor/dtype references")
        expected_tail = ["MEMOIZE", "TUPLE2", "MEMOIZE", "REDUCE", "MEMOIZE", "TUPLE2", "MEMOIZE"]
        if [entry[0] for entry in tokens[last + 1:last + 8]] != expected_tail:
            raise PickleLayoutError("unexpected scalar/tuple suffix")
        pieces, offsets, length = [], [], 0
        for index in range(first - 2, last + 8):
            name, arg, encoded = tokens[index]
            if index in indices:
                if name != "SHORT_BINBYTES":
                    raise PickleLayoutError("unsupported scalar payload encoding")
                offsets.append((length + 2, len(arg)))
            pieces.append(encoded)
            length += len(encoded)
        return b"".join(pieces), offsets

    template, fields = extract(payloads[3:6])
    other, other_fields = extract(payloads[6:9])
    sizes = (np.dtype(int).itemsize, 8, 8)
    if tuple(size for _, size in fields) != sizes or fields != other_fields or len(template) != len(other):
        raise PickleLayoutError("unexpected native integer/float64 payload sizes")
    names, formats, offsets, constants = [], [], [], []
    cursor = 0
    for field, dtype, (offset, size) in zip(("key", "score", "distance"), (np.dtype(int), np.dtype("f8"), np.dtype("f8")), fields):
        if cursor < offset:
            name = "constant_{}".format(len(constants))
            constant = template[cursor:offset]
            if other[cursor:offset] != constant:
                raise PickleLayoutError("NumPy records do not have a stable scalar layout")
            names.append(name); formats.append("V{}".format(len(constant))); offsets.append(cursor)
            constants.append((name, np.void(constant)))
        names.append(field); formats.append(dtype); offsets.append(offset)
        cursor = offset + size
    constant = template[cursor:]
    if other[cursor:] != constant:
        raise PickleLayoutError("unstable record suffix")
    names.append("constant_tail"); formats.append("V{}".format(len(constant))); offsets.append(cursor)
    constants.append(("constant_tail", np.void(constant)))
    dtype = np.dtype({"names": names, "formats": formats, "offsets": offsets, "itemsize": len(template)})
    return dtype, np.frombuffer(template, dtype=dtype)[0].copy(), constants


class OnePassScoreWriter:
    """A write-only sink for standard pickle.dump, with bounded patch buffers.

    Every output byte originates in that dump. Bulk records must match a
    runtime-generated fingerprint AND the exact source key/score/distance
    bytes. The scalar path validates payloads and NumPy reduction suffixes.
    Any unsupported stream triggers an explicit standard-dump fallback.
    """

    _SINGLE = set(b"(01N.Rabde}lsut]\x85\x86\x87\x88\x89\x90\x91\x93\x94")
    _FIXED = {ord("h"): 2, ord("j"): 5, ord("q"): 2, ord("r"): 5,
              ord("J"): 5, ord("K"): 2, ord("M"): 3, ord("G"): 9,
              0x80: 2, 0x95: 9, 0x82: 2, 0x83: 3, 0x84: 5}
    _LENGTH = {ord("C"): 1, 0x8c: 1, 0x8a: 1, ord("B"): 4,
               ord("X"): 4, 0x8b: 4, 0x8d: 8, 0x8e: 8, 0x96: 8}
    _SUFFIX = b"\x94\x86\x94R\x94"

    def __init__(self, raw_handle, z_handle, dictionaries, mean, sigma, top_n):
        leading = next((i for i, data in enumerate(dictionaries) if data), len(dictionaries))
        self.dtype, self.template, self.constants = scalar_record_layout(leading)
        self.raw_handle, self.z_handle = raw_handle, z_handle
        self.dictionaries = dictionaries
        self.mean, self.sigma, self.top_n = mean, sigma, top_n
        self.score_sum = np.zeros(mean.size, dtype=np.float64)
        self.pending = b""
        self.frame_remaining = None
        self.file_index = -1
        self.entries = None
        self.file_records = 0
        self.total_records = sum(map(len, dictionaries))
        self.completed_records = self.bulk_records = 0
        self.phase = 0  # next scalar: key, score, distance
        self.suffix = b""
        self.current = None
        self.failure = None
        self.stopped = False
        self.raw_bytes = self.z_bytes = 0
        self.patch_started = self.last_progress = time.monotonic()

    def _new_dictionary(self):
        if self.phase or self.suffix:
            raise PickleLayoutError("dictionary starts inside a scalar record")
        if self.file_index >= 0 and self.file_records != len(self.dictionaries[self.file_index]):
            raise PickleLayoutError("previous dictionary record count differs")
        self.file_index += 1
        if self.file_index >= len(self.dictionaries):
            raise PickleLayoutError("extra dictionary in pickle stream")
        self.entries = iter(self.dictionaries[self.file_index].items())
        self.file_records = 0

    def _next_record(self):
        if self.entries is None:
            raise PickleLayoutError("scalar payload outside a particle dictionary")
        try:
            serial, pair = next(self.entries)
        except StopIteration as exc:
            raise PickleLayoutError("too many serialized particle records") from exc
        raw_score, distance = pair
        z_score = raw_score
        if 0 <= serial < self.mean.size:
            z_score = (raw_score - self.mean[serial]) / float(self.sigma[serial])
            if self.file_index < self.top_n:
                self.score_sum[serial] += z_score
        return serial, raw_score, distance, z_score

    def _bulk(self, data, position, limit):
        if self.phase or self.suffix or self.entries is None:
            return None
        available = len(self.dictionaries[self.file_index]) - self.file_records
        count = min((limit - position) // self.dtype.itemsize, available, 8192)
        if count < 2:
            return None
        actual = np.frombuffer(data, dtype=self.dtype, count=count, offset=position)
        valid = np.ones(count, dtype=bool)
        for name, value in self.constants:
            valid &= actual[name] == value
        invalid = np.flatnonzero(~valid)
        if invalid.size:
            count = int(invalid[0])
        if not count:
            return None
        # A control opcode (SETITEMS/MARK/FRAME) ends the contiguous run.
        expected = np.empty(count, dtype=self.dtype)
        expected[:] = self.template
        keys, scores, distances = expected["key"], expected["score"], expected["distance"]
        normalized = np.empty(count, dtype=np.float64)
        for index in range(count):
            serial, raw_score, distance, z_score = self._next_record()
            keys[index], scores[index], distances[index], normalized[index] = serial, raw_score, distance, z_score
        length = count * self.dtype.itemsize
        if expected.tobytes() != data[position:position + length]:
            raise PickleLayoutError("serialized record bytes differ from source data")
        scores[:] = normalized
        self.file_records += count
        self.completed_records += count
        self.bulk_records += count
        return length, expected.tobytes()

    def _opcode_length(self, data, position, limit):
        code = data[position]
        if code in self._SINGLE:
            return 1
        if code in self._FIXED:
            length = self._FIXED[code]
            return length if position + length <= limit else None
        width = self._LENGTH.get(code)
        if width is None:
            raise PickleLayoutError("unsupported pickle opcode 0x{:02x}".format(code))
        header = 1 + width
        if position + header > limit:
            return None
        size = int.from_bytes(data[position + 1:position + header], "little")
        if size > 1024 * 1024:
            raise PickleLayoutError("unexpected large non-record payload")
        length = header + size
        return length if position + length <= limit else None

    def _scalar_payload(self, encoded):
        if self.suffix:
            raise PickleLayoutError("new payload before scalar reduction completes")
        if self.phase == 0:
            self.current = self._next_record()
        scalar = self.current[self.phase]
        raw_bytes = scalar.tobytes()
        if encoded != b"C" + bytes([len(raw_bytes)]) + raw_bytes:
            raise PickleLayoutError("scalar payload differs from the expected key/score/distance")
        replacement = encoded
        if self.phase == 1:
            replacement = encoded[:2] + self.current[3].tobytes()
        self.phase = (self.phase + 1) % 3
        self.suffix = self._SUFFIX + (b"\x86\x94" if self.phase == 0 else b"")
        if self.phase == 0:
            self.file_records += 1
            self.completed_records += 1
            self.current = None
        return replacement

    def _feed(self, incoming):
        data = self.pending + incoming
        position = 0
        pieces = []
        while position < len(data):
            if self.stopped:
                raise PickleLayoutError("bytes after pickle STOP")
            limit = len(data)
            if self.frame_remaining is not None:
                limit = min(limit, position + self.frame_remaining)
            bulk = self._bulk(data, position, limit)
            if bulk is not None:
                length, replacement = bulk
                pieces.append(replacement)
            else:
                length = self._opcode_length(data, position, limit)
                if length is None:
                    if self.frame_remaining is not None and len(data) - position >= self.frame_remaining:
                        raise PickleLayoutError("pickle opcode crosses a FRAME boundary")
                    break
                code = data[position]
                encoded = data[position:position + length]
                if code == 0x95:  # FRAME is metadata, never part of a record.
                    if self.frame_remaining is not None:
                        raise PickleLayoutError("nested/incomplete pickle FRAME")
                    self.frame_remaining = int.from_bytes(encoded[1:], "little")
                    if not self.frame_remaining:
                        self.frame_remaining = None
                    pieces.append(encoded)
                    position += length
                    continue
                if self.suffix:
                    if length != 1 or encoded != self.suffix[:1]:
                        raise PickleLayoutError("unexpected NumPy scalar reduction suffix")
                    self.suffix = self.suffix[1:]
                elif code == ord("}"):
                    self._new_dictionary()
                elif code == ord("C"):
                    encoded = self._scalar_payload(encoded)
                elif code in (ord("B"), 0x8e, 0x96):
                    raise PickleLayoutError("unsupported scalar byte-payload encoding")
                elif code == 0x80:
                    if encoded[1] != pickle.DEFAULT_PROTOCOL:
                        raise PickleLayoutError("unexpected pickle protocol")
                elif code == ord("."):
                    self.stopped = True
                pieces.append(encoded)
            position += length
            if self.frame_remaining is not None:
                self.frame_remaining -= length
                if self.frame_remaining == 0:
                    self.frame_remaining = None
        self.pending = data[position:]
        if pieces:
            outgoing = b"".join(pieces)
            self.z_handle.write(outgoing)
            self.z_bytes += len(outgoing)

    def write(self, data):
        data = bytes(data)
        self.raw_handle.write(data)
        self.raw_bytes += len(data)
        if self.failure is None:
            try:
                self._feed(data)
            except PickleLayoutError as exc:
                self.failure = str(exc)
                self.pending = b""
        now = time.monotonic()
        if now - self.last_progress >= 15:
            print("Pickle output: {:.2f} GiB raw, {}/{} records checked".format(
                self.raw_bytes / (1024.0 ** 3), self.completed_records, self.total_records), flush=True)
            self.last_progress = now
        return len(data)

    def finish(self):
        if self.failure is not None:
            return False
        valid = (not self.pending and not self.suffix and self.phase == 0 and self.stopped
                 and self.frame_remaining is None and self.raw_bytes == self.z_bytes
                 and self.file_index + 1 == len(self.dictionaries)
                 and self.completed_records == self.total_records
                 and (self.file_index < 0 or self.file_records == len(self.dictionaries[self.file_index])))
        if not valid:
            self.failure = "incomplete stream, dictionary counts or output byte lengths"
        return valid


def write_both_pickles(dictionaries, mean, sigma, top_n, raw_handle, z_handle):
    """Standard raw dump plus validated streaming score replacement."""
    writer = None
    try:
        writer = OnePassScoreWriter(raw_handle, z_handle, dictionaries, mean, sigma, top_n)
    except (ValueError, IndexError, TypeError) as exc:
        reason = str(exc)
    if writer is not None:
        with np.errstate(divide="ignore", invalid="ignore", over="ignore"):
            pickle.dump(dictionaries, writer)
        if writer.finish():
            return writer.score_sum, {"pickle_method": "single_standard_dump",
                                      "pickle_bytes_each": writer.raw_bytes,
                                      "bulk_patched_records": writer.bulk_records}
        reason = writer.failure
    else:
        pickle.dump(dictionaries, raw_handle)
    # The raw stream remains complete and unmodified. Discard partial ZS.
    print("Single-pass layout check failed ({}); using standard ZS pickle.dump fallback.".format(reason), flush=True)
    z_handle.seek(0)
    z_handle.truncate()
    sums = np.zeros(mean.size, dtype=np.float64)
    with np.errstate(divide="ignore", invalid="ignore", over="ignore"):
        for file_index, score_dict in enumerate(dictionaries):
            for serial, (raw_score, distance) in score_dict.items():
                if 0 <= serial < mean.size:
                    z_score = (raw_score - mean[serial]) / float(sigma[serial])
                    score_dict[serial] = (z_score, distance)
                    if file_index < top_n:
                        sums[serial] += z_score
    pickle.dump(dictionaries, z_handle)
    return sums, {"pickle_method": "standard_fallback", "fallback_reason": reason}


def compute_scores(file_dist_pairs, top_n, prefix, tmpdir=None):
    # tmpdir is retained as an API/CLI compatibility argument; no array spool.
    first_ids, first_raw, first_dist = read_search_scores(*file_dist_pairs[0])
    total = first_ids.size
    sums = np.zeros(total, dtype=np.float64)
    sum_squares = np.zeros(total, dtype=np.float64)
    counts = np.zeros(total, dtype=np.float64)
    outside = int(np.count_nonzero(first_ids >= total))
    progress_step = max(1, len(file_dist_pairs) // 20)
    last_progress = time.monotonic()
    dictionaries = []
    for i, (path, distance) in enumerate(file_dist_pairs):
        if i == 0:
            ids, raw, distances = first_ids, first_raw, first_dist
        else:
            ids, raw, distances = read_search_scores(path, distance)
        keep = (ids >= 0) & (ids < total)
        positions, values = ids[keep], raw[keep]
        sums[positions] += values
        squared = np.fromiter((value ** 2 for value in values), dtype=np.float64, count=values.size)
        sum_squares[positions] += squared
        counts[positions] += 1.0
        # Construct the exact original dictionary now, while arrays are live.
        # No np.save/np.load round trip and no second parse of input text.
        dictionaries.append(dict(zip(ids, zip(raw, distances))))
        if i == 0:
            del first_ids, first_raw, first_dist
        now = time.monotonic()
        if (i + 1) % progress_step == 0 or i + 1 == len(file_dist_pairs) or now - last_progress > 15:
            print("Read and accumulated {}/{} search files".format(i + 1, len(file_dist_pairs)), flush=True)
            last_progress = now
    del ids, raw, distances, keep, positions, values, squared
    observed = counts > 0
    incomplete = observed & (counts != len(file_dist_pairs))
    if np.any(incomplete):
        examples = np.flatnonzero(incomplete)[:8].tolist()
        raise ValueError(
            "Inconsistent particle serials across search files (examples: {}). "
            "As in v2p6, every normalized serial must occur in every file.".format(examples)
        )
    mean = np.zeros(total, dtype=np.float64)
    sigma = np.zeros(total, dtype=np.float64)
    for serial in np.flatnonzero(observed):
        count = float(counts[serial])
        average = sums[serial] / count
        square_average = sum_squares[serial] / count
        mean[serial] = average
        try:
            sigma[serial] = math.sqrt(square_average - average ** 2)
        except ValueError as exc:
            raise ValueError(
                "Negative variance for serial {} in v2p6's E[x^2]-E[x]^2 formula. "
                "Normalization has not been silently changed.".format(serial)
            ) from exc
    del sums, sum_squares, counts
    raw_path, z_path = pickle_paths(prefix)
    print("Writing BOTH complete pickles with one standard serialization...", flush=True)
    with atomic_binary_file(raw_path) as raw_handle, atomic_binary_file(z_path) as z_handle:
        score_sum, serialization = write_both_pickles(dictionaries, mean, sigma, top_n, raw_handle, z_handle)
    print("Pickle method: {}".format(serialization["pickle_method"]), flush=True)
    eligible = observed if top_n > 0 else np.ones(total, dtype=bool)
    info = {
        "total_particle_number": int(total),
        "scored_particle_number": int(np.count_nonzero(eligible)),
        "outside_legacy_bound": outside,
        "zero_variance_count": int(np.count_nonzero(eligible & (sigma == 0))),
        **serialization,
    }
    return np.flatnonzero(eligible).astype(np.int64, copy=False), score_sum[eligible], info


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(4 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def verify_pickle_files(prefix, reference_prefix):
    """Compare complete file bytes without loading/executing either pickle."""
    mismatches = []
    for path, reference in zip(pickle_paths(prefix), pickle_paths(reference_prefix)):
        expected_size, actual_size = os.path.getsize(reference), os.path.getsize(path)
        expected_hash, actual_hash = sha256_file(reference), sha256_file(path)
        equal = expected_size == actual_size and expected_hash == actual_hash
        print("{}: {} ({} bytes; SHA-256 {})".format(
            os.path.basename(path), "BYTE-IDENTICAL" if equal else "DIFFERENT", actual_size, actual_hash))
        if not equal:
            print("  Reference: {} bytes; SHA-256 {}".format(expected_size, expected_hash))
            mismatches.append(os.path.basename(path))
    if mismatches:
        raise ValueError(
            "Pickle verification differs for {}. The reference must be freshly regenerated "
            "by v2p6 with identical inputs/parameters in the same Python/NumPy/SciPy runtime.".format(", ".join(mismatches)))


def file_stamp(path):
    stat = os.stat(path)
    return [os.path.abspath(path), stat.st_size, stat.st_mtime_ns]


def cache_signature(args, pairs, top_n):
    return {
        "format": _CACHE_FORMAT,
        "numpy_version": np.__version__,
        "scipy_version": scipy.__version__,
        "python_version": platform.python_version(),
        "python_implementation": platform.python_implementation(),
        "pickle_protocol": pickle.DEFAULT_PROTOCOL,
        "native_int_dtype": np.dtype(int).str,
        "byteorder": sys.byteorder,
        "files": [file_stamp(path) for path, _ in pairs],
        "best_string": args.best_string,
        "diameter": args.diameter,
        "top_n": top_n,
    }


def load_score_cache(path, signature, prefix):
    if not os.path.isfile(path):
        return None
    try:
        with np.load(path, allow_pickle=False) as cache:
            metadata = json.loads(str(cache["metadata"].item()))
            if metadata["signature"] != signature:
                print("Input files or score parameters changed; rebuilding pickle outputs.")
                return None
            if metadata["pickle_files"] != [file_stamp(p) for p in pickle_paths(prefix)]:
                print("Pickle outputs changed or are incomplete; rebuilding them.")
                return None
            ids = cache["serial_numbers"]
            scores = cache["top_n_scores"]
            if ids.dtype != np.dtype("int64") or scores.dtype != np.dtype("float64"):
                raise ValueError("invalid score cache dtypes")
            if ids.ndim != 1 or scores.shape != ids.shape:
                raise ValueError("invalid score cache shapes")
            if np.any(ids < 0) or np.any(ids[1:] <= ids[:-1]):
                raise ValueError("invalid cached serial numbers")
            return ids, scores, metadata["info"]
    except (OSError, ValueError, KeyError, EOFError) as exc:
        print("Could not reuse score cache ({}); rebuilding.".format(exc))
        return None


def save_score_cache(path, signature, prefix, ids, scores, info):
    metadata = {
        "signature": signature,
        "pickle_files": [file_stamp(p) for p in pickle_paths(prefix)],
        "info": info,
    }
    with atomic_binary_file(path) as handle:
        # No compression: compact final arrays are cheap to write and load.
        np.savez(handle, metadata=np.array(json.dumps(metadata, sort_keys=True)),
                 serial_numbers=ids, top_n_scores=scores)


def write_selections(prefix, ids, scores, threshold):
    good_mask = scores >= threshold
    good_ids, bad_ids = ids[good_mask], ids[~good_mask]
    np.savetxt(prefix + "_sel_good.txt", good_ids, fmt="%d")
    np.savetxt(prefix + "_sel_bad.txt", bad_ids, fmt="%d")
    return good_ids, bad_ids


def pick_star(starfile, prefix, good_ids, bad_ids):
    """Copy selected zero-based PHYSICAL lines, retaining the STAR header."""
    good_set, bad_set = set(good_ids.tolist()), set(bad_ids.tolist())
    with open(starfile, "r") as source:
        header = []
        in_loop, image_loop = False, False
        for line in source:
            stripped = line.strip()
            if stripped == "loop_":
                in_loop, image_loop = True, False
            elif stripped.startswith("data_"):
                in_loop, image_loop = False, False
            elif in_loop and stripped.startswith("_rlnImageName"):
                image_loop = True
            elif (image_loop and stripped and
                  not stripped.startswith(("_", "#"))):
                first_data = line
                break
            header.append(line)
        else:
            raise ValueError("Could not locate a particle loop with _rlnImageName in the STAR file.")
        print("star mline = {}".format(len(header)))
        with open(prefix + "_goodpick.star", "w") as good, \
                open(prefix + "_badpick.star", "w") as bad:
            good.writelines(header)
            bad.writelines(header)
            line_count = 0
            for index, line in enumerate(chain(header, [first_data], source)):
                line_count = index + 1
                if index in good_set:
                    good.write(line)
                if index in bad_set:
                    bad.write(line)
            if (good_set and max(good_set) >= line_count) or (bad_set and max(bad_set) >= line_count):
                raise ValueError("A selected serial exceeds the STAR file's physical line count.")


def process_searchfile(filename, set_good, set_bad, suffix):
    try:
        with open(filename, "r") as source, \
                open(filename + suffix + "_good.txt", "w") as good, \
                open(filename + suffix + "_bad.txt", "w") as bad:
            for record, first in enumerate(source, 1):
                second, third = source.readline(), source.readline()
                if not second or not third:
                    raise ValueError("incomplete three-line record {}".format(record))
                serial = int(first.split(",", 2)[1])
                if serial in set_good:
                    good.writelines((first, second, third))
                if serial in set_bad:
                    bad.writelines((first, second, third))
        return None
    except (OSError, ValueError, IndexError) as exc:
        return "Error processing {}: {}".format(filename, exc)


def generate_searchfiles(paths, good_ids, bad_ids, args):
    good_set, bad_set = set(good_ids.tolist()), set(bad_ids.tolist())

    def worker(path):
        return process_searchfile(path, good_set, bad_set, args.searchfile_suffix)

    # Filtering has already deduplicated path strings; keep the guard for
    # callers that invoke this helper directly.
    with ThreadPoolExecutor(max_workers=args.max_cpu) as executor:
        errors = [error for error in executor.map(worker, dict.fromkeys(paths)) if error]
    if errors:
        raise ValueError("\n".join(errors))


def histogram_counts(scores):
    thresholds = np.linspace(-1.0, 5.0, 61)
    good = np.array([np.count_nonzero(scores >= threshold) for threshold in thresholds])
    return thresholds, good, scores.size - good


def draw_histogram(scores, args):
    if args.no_plot and not args.histogram_png:
        return
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise RuntimeError("Matplotlib is needed for the plot; install it or pass --no_plot.") from exc
    thresholds, good, bad = histogram_counts(scores)
    plt.figure(figsize=(10, 6))
    plt.plot(thresholds, good, label="Good", linewidth=2)
    plt.plot(thresholds, bad, label="Bad", linewidth=2)
    plt.xlabel("Top N Sum Threshold")
    plt.ylabel("Particle Count")
    plt.title("Good/Bad Particles vs. Top N Sum Threshold")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    if args.histogram_png:
        plt.savefig(args.histogram_png, dpi=150)
    if not args.no_plot:
        plt.show()
    plt.close()


def create_pick_parser():
    parser = argparse.ArgumentParser(
        description="Pick GisAPR particles; generate BOTH complete v2p6-compatible pickles with one standard serialization.")
    parser.add_argument("--i", required=True, help="Input index, e.g. generated by ls search*.txt > index.txt.")
    parser.add_argument("--best_string", required=True,
                        help="Transform marker of the best-fit PDB; rot/tilt/psi encode rotation-vector components in degrees.")
    parser.add_argument("--o", required=True, help="Output prefix; original .pkl and selection filenames are retained.")
    parser.add_argument("--diameter", type=float, default=70, help="Estimated subunit diameter in Angstrom (default: 70).")
    parser.add_argument("--top_N", type=int, default=5, help="Number of nearest positions to sum (default: 5).")
    parser.add_argument("--top_N_sum_threshold", type=float, default=1.0, help="Good if top-N Z-score sum >= this value.")
    parser.add_argument("--regenerate_pickel", "--regenerate_pickle", action="store_true",
                        help="Regenerate BOTH complete pickle files and the score cache.")
    parser.add_argument("--do_generate_searchfile", action="store_true", help="Write selected good/bad search files for retained inputs only.")
    parser.add_argument("--searchfile_suffix", default="_picked", help="Selected search-file suffix (default: _picked).")
    parser.add_argument("--do_pick_star", action="store_true", help="Write selected good/bad STAR files.")
    parser.add_argument("--starfile", default=None, help="STAR file for --do_pick_star.")
    parser.add_argument("--max_cpu", type=int, default=6, help="Threads for optional search-file output (default: 6).")
    parser.add_argument("--tmpdir", default=None, help="Accepted for compatibility; v3p3 no longer writes intermediate array files.")
    parser.add_argument("--no_cache", action="store_true", help="Do not use/write the compact score cache; still write BOTH .pkl files.")
    parser.add_argument("--no_plot", action="store_true", help="Do not display the histogram window.")
    parser.add_argument("--histogram_png", default=None, help="Optional histogram image filename; also works with --no_plot.")
    parser.add_argument("--verify_against_prefix", default=None,
                        help="Compare both complete output pickles byte-for-byte with a freshly generated v2p6 prefix.")
    parser.add_argument("--version", action="version", version="%(prog)s " + __version__)
    return parser


def main(argv=None):
    parser = create_pick_parser()
    args = parser.parse_args(argv)
    if not math.isfinite(args.diameter) or args.diameter <= 0:
        parser.error("--diameter must be finite and positive")
    if args.max_cpu < 1:
        parser.error("--max_cpu must be at least 1")
    if args.do_pick_star and not args.starfile:
        parser.error("--do_pick_star requires --starfile")
    if args.tmpdir is not None and not os.path.isdir(args.tmpdir):
        parser.error("--tmpdir must be an existing directory")
    if args.verify_against_prefix is not None:
        if os.path.abspath(args.verify_against_prefix) == os.path.abspath(args.o):
            parser.error("--verify_against_prefix must differ from --o")
        for reference in pickle_paths(args.verify_against_prefix):
            if not os.path.isfile(reference):
                parser.error("Reference pickle does not exist: {}".format(reference))
    start = time.perf_counter()
    paths = filter_search_files(read_index(args.i))
    pairs = sorted_file_distances(paths, args.best_string, args.diameter)
    if args.top_N > len(pairs):
        print("Warning! --top_N is more than the actual number of search files.")
    top_n = max(0, min(args.top_N, len(pairs)))
    signature = cache_signature(args, pairs, top_n)
    cache_path = args.o + "_pick_cache_v3p3.npz"
    cached = None
    if not args.regenerate_pickel and not args.no_cache:
        cached = load_score_cache(cache_path, signature, args.o)
    if cached is None:
        if any(os.path.exists(path) for path in pickle_paths(args.o)):
            print("Rebuilding both complete, v2p6-compatible .pkl outputs.", flush=True)
        ids, scores, info = compute_scores(pairs, top_n, args.o, args.tmpdir)
        if not args.no_cache:
            try:
                save_score_cache(cache_path, signature, args.o, ids, scores, info)
            except OSError as exc:
                print("Warning: pickle outputs are complete, but the optional score cache could not be saved: {}".format(exc))
    else:
        ids, scores, info = cached
        print("Reused compact score cache; both complete .pkl outputs are present.")
    print("Total number of particles: ", info["total_particle_number"])
    if info["outside_legacy_bound"]:
        print("Compatibility note: {} serials are outside v2p6's normalization/selection bound; "
              "their complete raw entries remain in BOTH pickles.".format(info["outside_legacy_bound"]))
    if info["zero_variance_count"]:
        print("Compatibility note: {} scored particles have zero variance; non-finite scores compare as in v2p6.".format(
            info["zero_variance_count"]))
    good, bad = write_selections(args.o, ids, scores, args.top_N_sum_threshold)
    print("Good = {}, bad = {}".format(float(good.size), float(bad.size)))
    if args.do_pick_star:
        pick_star(args.starfile, args.o, good, bad)
    if args.do_generate_searchfile:
        generate_searchfiles(paths, good, bad, args)
    if args.verify_against_prefix is not None:
        verify_pickle_files(args.o, args.verify_against_prefix)
    print("Processing completed in {:.3f} s (before displaying the plot).".format(time.perf_counter() - start), flush=True)
    draw_histogram(scores, args)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (OSError, ValueError, RuntimeError, MemoryError) as exc:
        print("Error: {}".format(exc), file=sys.stderr)
        sys.exit(1)
